n = input ('Digite algo?')
print('O tipo primitivo desse valor e:'), type(n)
print('So tem espacos?', n.isspace())
print('E um numero?', n.isnumeric())
print('E um alfabeto?', n.isalpha())
print('E um alphanumerico?', n.isalnum())
print('Esta em maiusculas?', n.isupper())
print('Esta em minuscula?', n.islower())
print('Esta capitaliado?', n.istittle())
